version: "3.9"  # Use the Docker compose version 3.9

services:
  # Service for the Node.js Express application
  backend-motiv-app:
    # build: ./backend  # Directory containing the backend Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "3000:3000"    # Map port 3000 from the host to port 3000 in the container
    volumes:
      - .:/app
    working_dir: /usr/src/app/backend
    # networks:
    #   - motiv-app

  # Service for the React Native Expo application
  frontend-motiv-app:
    # build: ./frontend # Directory containing the frontend Dockerfile
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - ANDROID_HOME=/root/Android/sdk
    stdin_open: true
    tty: true
    # ports:
    #   - "19000:19000"  # Map port 19000 from the host to port 19000 in the container
    #   - "19001:19001"  # Map port 19001 from the host to port 19001 in the container
    #   - "19002:19002"  # Map port 19002 from the host to port 19002 in the container
    #   - "19006:19006"  # Map port 19006 from the host to port 19006 in the container
    volumes:
      - ./frontend:/opt/frontend/app:delegated
      - ./frontend/package.json:/opt/frontend/package.json
      - ./frontend/package-lock.json:/opt/frontend/package-lock.json
      - $HOME/Android/Sdk:/root/Android/sdk
    working_dir: /usr/src/app/frontend
    # networks:
    #   - motiv-app
    depends_on:
      - backend-motiv-app
    network_mode: host

  # Service for MongoDB Atlas (Cloud MongoDB)
  mongodb:
    image: mongo:latest   # Use the latest official MongoDB image from Docker Hub
    environment:
      MONGO_INITDB_ROOT_USERNAME: "motivadmindb"  # MongoDB Atlas username
      MONGO_INITDB_ROOT_PASSWORD: "LfTnT8RneaZhslRr"  # MongoDB Atlas password
    command: mongod --replSet rs0  # (I don't fully understand for now, maybe comment it / get back to it later) Set up MongoDB as a replica set for Atlas 
    ports:
      - "27017:27017"  # Map port 27017 from the host to port 27017 in the container

# A network configuration to separate the services
# In this example, the default bridge network is used,
# which allows the containers to communicate with each other using their service names as hostnames.
networks:
  motiv-app:
    driver: bridge
